// Project : BarberShop - Gestion des rendez-vous d'un salon de coiffure

// FILE : Client.java
// PACKAGE : model

// FR : Cette classe représente un client dans l'application.
// EN : This class represents a client in the application.
// PT : Esta classe representa um cliente na aplicacao.

// AUTHOR : Bauwens Thomas
// STATUS : DONE

package model;

// FR : On importe la classe LocalDateTime pour gérer la date de création du client.
// EN : We import the LocalDateTime class to manage the client's creation date.
// PT : Importamos a classe LocalDateTime para gerenciar a data de criação do cliente.
import java.time.LocalDateTime;

// FR : La classe Client contient les informations d'un client, telles que son nom, prénom, téléphone et email. Elle inclut également des méthodes pour accéder et modifier ces informations.
// EN : The Client class contains the information of a client, such as their name, first name, phone number, and email. It also includes methods to access and modify this information.
// PT : A classe Client contém as informações de um cliente, como seu nome, sobrenome, número de telefone e email. Ela também inclui métodos para acessar e modificar essas informações.
public class Client {
    private int id;   
    private String nom;
    private String prenom;
    private String telephone;
    private String email;
    private LocalDateTime createdAt;

    // FR : Constructeurs avec et sans id pour permettre la création d'un client avec ou sans spécifier l'id (l'id sera généré par la base de données lors de l'insertion).
    // EN : Constructors with and without id to allow creating a client with or without specifying the id (the id will be generated by the database when inserting).
    // PT : Construtores com e sem id para permitir a criação de um cliente com ou sem especificar o id (o id será gerado pelo banco de dados ao inserir).
    public Client(int id, String nom, String prenom, String telephone, String email) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.telephone = telephone;
        this.email = email;
    }

    // FR : Constructeur sans id pour la création d'un client avant l'insertion en base de données.
    // EN : Constructor without id for creating a client before inserting into the database.
    // PT : Construtor sem id para criar um cliente antes de inserir no banco de dados.
    public Client(String nom, String prenom, String telephone, String email) {
        this.nom = nom;
        this.prenom = prenom;
        this.telephone = telephone;
        this.email = email;
    }

    // FR : Getters et setters pour accéder et modifier les informations du client.
    // EN : Getters and setters to access and modify the client's information.
    // PT : Getters e setters para acessar e modificar as informações do cliente.
    public int getId() {
        return id;
    }

    // FR : Le setter pour l'id est privé car l'id doit être géré par la base de données et ne doit pas être modifié manuellement.
    // EN : The setter for id is private because the id should be managed by the database and should not be modified manually.
    // PT : O setter para id é privado porque o id deve ser gerenciado pelo banco de dados e não deve ser modificado manualmente.
    public String getNom() {
        return nom;
    }

    // FR : Le setter pour le nom est privé car le nom d'un client ne doit pas être modifié après sa création.
    // EN : The setter for the name is private because a client's name should not be modified after creation.
    // PT : O setter para o nome é privado porque o nome de um cliente não deve ser modificado após a criação.
    public String getPrenom() {
        return prenom;
    }

    // FR : Le setter pour le prénom est privé car le prénom d'un client ne doit pas être modifié après sa création.
    // EN : The setter for the first name is private because a client's first name should not be modified after creation.
    // PT : O setter para o sobrenome é privado porque o sobrenome de um cliente não deve ser modificado após a criação.
    public String getTelephone() {
        return telephone;
    }

    // FR : Le setter pour le téléphone est privé car le numéro de téléphone d'un client ne doit pas être modifié après sa création.
    // EN : The setter for the phone number is private because a client's phone number should not be modified after creation.
    // PT : O setter para o número de telefone é privado porque o número de telefone de um cliente não deve ser modificado após a criação.
    public String getEmail() {
        return email;
    }

    // FR : Le setter pour l'email est privé car l'email d'un client ne doit pas être modifié après sa création.
    // EN : The setter for the email is private because a client's email should not be modified after creation.
    // PT : O setter para o email é privado porque o email de um cliente não deve ser modificado após a criação.
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    // FR : Le setter pour l'email est privé car l'email d'un client ne doit pas être modifié après sa création.
    // EN : The setter for the email is private because a client's email should not be modified after creation.
    // PT : O setter para o email é privado porque o email de um cliente não deve ser modificado após a criação.
    public void setEmail(String email) {
        this.email = email;
    }

    // FR : toString pour afficher les informations du client de manière lisible.
    // EN : toString to display the client's information in a readable way.
    // PT : toString para exibir as informações do cliente de maneira legível.
    @Override
    public String toString() {
        return "Client{" +
                "id=" + id +
                ", nom='" + nom + '\'' +
                ", prenom='" + prenom + '\'' +
                ", telephone='" + telephone + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}